# Disable mTLS for connections to the API server
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: k8s-api-mtls-disable
  namespace: s0-system
spec:
  host: "kubernetes.default.svc"
  trafficPolicy:
    tls:
      mode: DISABLE
