apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kedacore/keda/releases/download/v2.9.3/keda-2.9.3.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/tags/v0.81.0/bundle.yaml

configMapGenerator:
  - files:
      - envoy-config.yaml
    name: envoy-config
    namespace: s0-system
    options:
      disableNameSuffixHash: true