apiVersion: v1
kind: ServiceAccount
metadata:
  name: s0
  namespace: s0-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s0
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments/scale" ]
    verbs: [ "get", "watch", "list", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s0
subjects:
  - kind: ServiceAccount
    name: s0
    namespace: s0-system
roleRef:
  kind: ClusterRole
  name: s0
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0
  namespace: s0-system
  labels:
    app: s0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0
  template:
    metadata:
      labels:
        app: s0
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: s0
      containers:
        - name: backend
          image: ko://github.com/pierdipi/s0/ext
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: s0
  namespace: s0-system
spec:
  selector:
    app: s0
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      appProtocol: grpc
